version: '3'

services:
  # go-api:
  #   build:
  #     context: ./backend  # Path to your GoLang API code
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - react-app

  # react-app:
  #   build:
  #     context: ./frontend  # Path to your React app code
  #   ports:
  #     - "3000:3000"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: golang
      MYSQL_USER: goteam
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"